name: baepoyml

on:
  push:
    branches:
      - main  # main 브랜치로 푸시될 때 트리거

jobs:
  baepo:
    runs-on: ubuntu-latest  # 실행할 환경 (예: 우분투)
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 리포지토리 코드를 체크아웃

      - name: Give execute permission to gradlew
        run: chmod +x ./gradlew  # gradlew에 실행 권한 부여

      - name: Give execute permission to deploy script
        run: chmod +x ./deploy.sh  # deploy.sh에 실행 권한 부여

      - name: Set up MySQL credentials
        env:
          DB_USER: ${{ secrets.DB_USER }}  # GitHub secrets에서 값 가져오기
          DB_PASS: ${{ secrets.DB_PASS }}
        run: |
          echo "DB_USER=${DB_USER}" >> .env
          echo "DB_PASS=${DB_PASS}" >> .env

      - name: Build project
        run: |
          ./gradlew build  # Gradle로 프로젝트 빌드

      - name: Deploy application
        run: |
          ./deploy.sh  # 배포 스크립트 실행
